//! `cbld migrate --from=cmake`
//!
//! A deliberately naive, pattern-based parser for `CMakeLists.txt`. It
//! recognizes a handful of canonical primitives — `project`,
//! `add_executable`, `add_library`, `target_include_directories`,
//! `target_link_libraries` — and emits a starter `cbld.toml`. CMake's
//! scripting constructs (`foreach`, `function`, `if`, generator expressions,
//! ...) are not interpreted; when present, cbld just flags them so the user
//! knows to port that logic by hand. No CMake-parsing crate is pulled in —
//! this is plain string scanning, in keeping with cbld's "no heavy deps"
//! rule.

use std::fs;
use std::path::{Path, PathBuf};

use crate::cli::MigrateArgs;
use crate::error::{CbldError, IoPathExt, Result};

/// Run `cbld migrate`.
pub fn run(args: &MigrateArgs, quiet: bool) -> Result<()> {
    if args.from != "cmake" {
        return Err(CbldError::Config(format!(
            "migration from '{}' is not supported yet (only 'cmake' is implemented)",
            args.from
        )));
    }

    let root = args.path.clone().unwrap_or_else(|| PathBuf::from("."));
    let cmake_path = root.join("CMakeLists.txt");
    let text = fs::read_to_string(&cmake_path).path_ctx(&cmake_path)?;

    let project = parse_cmake(&text);

    let manifest_path = root.join("cbld.toml");
    if manifest_path.exists() {
        return Err(CbldError::LayoutViolation(format!(
            "{} already exists; refusing to overwrite",
            manifest_path.display()
        )));
    }
    fs::write(&manifest_path, project.render_manifest()).path_ctx(&manifest_path)?;

    if !quiet {
        println!(
            "\x1b[1;32m   Migrated\x1b[0m {} -> {}",
            cmake_path.display(),
            manifest_path.display()
        );
        project.print_notices();
    }
    Ok(())
}

/// Everything the naive parser managed to extract from a CMakeLists.txt.
///
/// Mixed C/C++ targets are native to cbld. The migrator still records a
/// dominant language solely to choose a familiar suggested entry-point name.
#[derive(Default)]
struct CMakeProject {
    name: Option<String>,
    is_library: bool,
    /// Dominant language: true if C "wins" the source-count majority.
    is_c: bool,
    /// Every source discovered in CMake target declarations.
    sources: Vec<String>,
    /// Whether both C and C++ sources were discovered.
    mixed: bool,
    include_dirs: Vec<String>,
    link_libs: Vec<String>,
    complex_hits: Vec<String>,
}

impl CMakeProject {
    fn render_manifest(&self) -> String {
        let name = self
            .name
            .clone()
            .unwrap_or_else(|| "my_project".to_string());

        let mut out = String::new();
        out.push_str("# Generated by `cbld migrate --from=cmake`.\n");
        out.push_str(
            "# Review the TODOs below — cbld's CMake parser only understands a few\n\
             # canonical primitives; loops, functions, and generator expressions are\n\
             # not interpreted and must be ported by hand.\n\n",
        );

        out.push_str("[package]\n");
        out.push_str(&format!("name = \"{name}\"\n"));
        out.push_str("version = \"0.1.0\"\n");
        if !self.include_dirs.is_empty() {
            let dirs: Vec<String> = self
                .include_dirs
                .iter()
                .map(|d| format!("\"{d}\""))
                .collect();
            out.push_str(&format!("include_dirs = [{}]\n", dirs.join(", ")));
        }
        let system_libs: Vec<String> = self
            .link_libs
            .iter()
            .filter(|l| is_system_lib(l))
            .map(|l| strip_lib_flag(l).to_string())
            .collect();
        if !system_libs.is_empty() {
            let libs: Vec<String> = system_libs.iter().map(|l| format!("\"{l}\"")).collect();
            out.push_str(&format!("libs = [{}]\n", libs.join(", ")));
        }
        out.push('\n');

        out.push_str("[features]\ndefault = []\n\n");

        if self.is_c || self.mixed {
            out.push_str("[profile.c]\nstandard = \"c17\"\nwarnings = [\"all\", \"extra\"]\noptimization = \"0\"\n\n");
        }
        if !self.is_c || self.mixed {
            out.push_str("[profile.cpp]\nstandard = \"c++20\"\nwarnings = [\"all\", \"extra\"]\noptimization = \"0\"\n\n");
        }

        out.push_str("[dependencies]\n");
        let other_libs: Vec<&String> = self
            .link_libs
            .iter()
            .filter(|l| !is_system_lib(l))
            .collect();
        if !other_libs.is_empty() {
            out.push_str(
                "# TODO: map these CMake target_link_libraries to cbld `gh:user/lib` deps\n\
                 # (cbld cannot infer a repository from a bare library name):\n",
            );
            for lib in other_libs {
                out.push_str(&format!(
                    "# \"gh:<user>/{lib}\" = \"x.y.z\"  # was: {lib}\n"
                ));
            }
        }

        if self.mixed {
            out.push_str("\n# This target mixes C and C++; cbld compiles each source with its matching profile.\n");
        }

        out
    }

    fn print_notices(&self) {
        if !self.sources.is_empty() {
            let entry = match (self.is_library, self.is_c) {
                (false, false) => "src/main.cpp",
                (false, true) => "src/main.c",
                (true, false) => "src/lib.cpp",
                (true, true) => "src/lib.c",
            };
            println!(
                "\x1b[1;33mnote\x1b[0m: cbld uses a strict layout — there is no \"sources\" \
                 list in cbld.toml. Move/merge these detected sources into {entry} by hand:"
            );
            for s in &self.sources {
                println!("         - {s}");
            }
        }
        if !self.complex_hits.is_empty() {
            println!(
                "\x1b[1;33mnote\x1b[0m: CMakeLists.txt uses constructs cbld does not parse \
                 ({}). Review the file manually for logic not captured above.",
                self.complex_hits.join(", ")
            );
        }
    }
}

fn is_cpp_source(name: &str) -> bool {
    matches!(
        Path::new(name).extension().and_then(|e| e.to_str()),
        Some("cc" | "cpp" | "cxx" | "c++" | "cp")
    )
}

/// Strip `#`-style line comments. CMake's rare `#[[ ]]` bracket comments are
/// left alone — a naive tool errs on the side of flagging unfamiliar syntax
/// rather than silently mis-parsing it.
fn strip_comments(text: &str) -> String {
    text.lines()
        .map(|line| line.split('#').next().unwrap_or(""))
        .collect::<Vec<_>>()
        .join("\n")
}

fn unquote(token: &str) -> String {
    let t = token.trim();
    for q in ['"', '\''] {
        if t.len() >= 2 && t.starts_with(q) && t.ends_with(q) {
            return t[1..t.len() - 1].to_string();
        }
    }
    t.to_string()
}

fn strip_lib_flag(name: &str) -> &str {
    name.strip_prefix("-l").unwrap_or(name)
}

fn is_system_lib(name: &str) -> bool {
    let name = strip_lib_flag(name);
    if name.is_empty() {
        return false;
    }
    if name.contains(['/', '\\', ':', '$', '<', '>', ';']) || name.contains("::") {
        return false;
    }
    let lower = name.to_ascii_lowercase();
    !(lower.ends_with(".a")
        || lower.ends_with(".so")
        || lower.ends_with(".lib")
        || lower.ends_with(".dylib"))
}

/// Find every invocation of `command(...)` and return the raw argument text
/// inside the parens. A depth-counted scan handles nested parens (CMake
/// `if()` conditions sometimes nest); it does not understand parens inside
/// quoted strings, an accepted limitation for a "naive" migration tool.
fn extract_calls(text: &str, command: &str) -> Vec<String> {
    let mut calls = Vec::new();
    let bytes = text.as_bytes();
    let needle = format!("{command}(");
    let lower_text = text.to_ascii_lowercase();
    let lower_needle = needle.to_ascii_lowercase();

    let mut search_from = 0;
    while search_from < lower_text.len() {
        let Some(rel) = lower_text[search_from..].find(&lower_needle) else {
            break;
        };
        let start = search_from + rel + needle.len();
        let mut depth = 1usize;
        let mut end = start;
        while end < bytes.len() && depth > 0 {
            match bytes[end] {
                b'(' => depth += 1,
                b')' => depth -= 1,
                _ => {}
            }
            end += 1;
        }
        if depth == 0 {
            calls.push(text[start..end - 1].to_string());
        }
        search_from = end.max(start + 1);
    }
    calls
}

fn parse_cmake(raw: &str) -> CMakeProject {
    let text = strip_comments(raw);
    let mut project = CMakeProject::default();

    if let Some(call) = extract_calls(&text, "project").into_iter().next() {
        let name = call.split_whitespace().next().map(unquote);
        if let Some(name) = name.filter(|n| !n.is_empty()) {
            project.name = Some(name);
        }
    }

    for call in extract_calls(&text, "add_executable") {
        let mut tokens = call.split_whitespace();
        let target = tokens.next().map(unquote);
        if project.name.is_none() {
            project.name = target;
        }
        project.sources.extend(tokens.map(unquote));
        project.is_library = false;
    }

    for call in extract_calls(&text, "add_library") {
        let mut tokens = call.split_whitespace();
        let target = tokens.next().map(unquote);
        if project.name.is_none() {
            project.name = target;
        }
        for tok in tokens {
            if matches!(tok, "STATIC" | "SHARED" | "MODULE" | "INTERFACE" | "OBJECT") {
                continue;
            }
            project.sources.push(unquote(tok));
        }
        project.is_library = true;
    }

    for call in extract_calls(&text, "target_include_directories") {
        let mut tokens = call.split_whitespace();
        tokens.next(); // target name — cbld has one implicit target per package
        for tok in tokens {
            if matches!(tok, "PUBLIC" | "PRIVATE" | "INTERFACE") {
                continue;
            }
            project.include_dirs.push(unquote(tok));
        }
    }

    for call in extract_calls(&text, "target_link_libraries") {
        let mut tokens = call.split_whitespace();
        tokens.next(); // target name
        for tok in tokens {
            if matches!(tok, "PUBLIC" | "PRIVATE" | "INTERFACE") {
                continue;
            }
            project.link_libs.push(unquote(tok));
        }
    }

    project.include_dirs.sort();
    project.include_dirs.dedup();
    project.link_libs.sort();
    project.link_libs.dedup();

    // Pick the dominant language only for migration hints. Ties favor C++,
    // matching `cbld init`'s own default; mixed targets remain intact.
    let cpp_count = project.sources.iter().filter(|s| is_cpp_source(s)).count();
    let c_count = project.sources.len() - cpp_count;
    project.is_c = c_count > cpp_count;

    project.mixed = cpp_count > 0 && c_count > 0;

    let lower = text.to_ascii_lowercase();
    for keyword in [
        "foreach(",
        "function(",
        "macro(",
        "while(",
        "generate_export_header(",
    ] {
        if lower.contains(keyword) {
            project
                .complex_hits
                .push(keyword.trim_end_matches('(').to_string());
        }
    }

    project
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A mock mixed-language `add_executable` call: 3 C++ sources and 2 C
    /// sources. The full set must be retained by the migration model.
    const MIXED_LANGUAGE_CMAKE: &str = r#"
        project(widgets)
        add_executable(widgets main.cpp foo.c bar.cpp baz.c qux.cpp)
        target_include_directories(widgets PUBLIC include)
        target_link_libraries(widgets pthread)
    "#;

    #[test]
    fn mixed_language_sources_are_retained() {
        let project = parse_cmake(MIXED_LANGUAGE_CMAKE);

        // 3 C++ vs. 2 C: C++ is dominant, so `is_c` must be false.
        assert!(!project.is_c);
        assert!(project.mixed);
        assert_eq!(project.sources.len(), 5);
        assert!(project.sources.iter().any(|s| s == "foo.c"));
        assert!(project.sources.iter().any(|s| s == "main.cpp"));
    }

    #[test]
    fn mixed_sources_emit_both_profiles_without_a_todo() {
        let project = parse_cmake(MIXED_LANGUAGE_CMAKE);
        let manifest = project.render_manifest();

        assert!(manifest.contains("# This target mixes C and C++"));
        assert!(manifest.contains("[profile.c]"));
        assert!(manifest.contains("[profile.cpp]"));
        assert!(manifest.contains("[package]"));
        assert!(manifest.contains("include_dirs = [\"include\"]"));
        assert!(manifest.contains("libs = [\"pthread\"]"));
        assert!(!manifest.contains("gh:<user>/pthread"));
        assert!(!manifest.contains("extra_flags"));
    }

    #[test]
    fn single_language_project_does_not_enable_mixed_profiles() {
        let text = r#"
            project(tool)
            add_executable(tool main.c util.c)
        "#;
        let project = parse_cmake(text);

        assert!(project.is_c);
        assert_eq!(project.sources.len(), 2);
        assert!(!project.mixed);

        let manifest = project.render_manifest();
        assert!(!manifest.contains("# This target mixes C and C++"));
        assert!(!manifest.contains("[profile.cpp]"));
    }

    #[test]
    fn cmake_link_libs_split_system_names_from_targets() {
        let text = r#"
            project(tool)
            add_executable(tool main.c)
            target_link_libraries(tool PUBLIC pthread m Foo::Bar /opt/libfoo.a)
        "#;
        let manifest = parse_cmake(text).render_manifest();
        assert!(manifest.contains("libs = [\"m\", \"pthread\"]"));
        assert!(manifest.contains("# \"gh:<user>/Foo::Bar\""));
        assert!(manifest.contains("# \"gh:<user>//opt/libfoo.a\""));
    }

    /// Reporting helpers must never panic, mixed-language or not — this is
    /// the migration tool's "never crash, always tell the user" guarantee.
    #[test]
    fn reporting_helpers_do_not_panic_on_mixed_or_clean_input() {
        let mixed = parse_cmake(MIXED_LANGUAGE_CMAKE);
        mixed.print_notices();
        let _ = mixed.render_manifest();

        let clean = parse_cmake("project(empty)");
        clean.print_notices();
        let _ = clean.render_manifest();
    }
}
